curl --location --request POST "https://devcamper.io/api/v1/auth/login" ^
  --header "Content-Type: application/json" ^
  --data "^
	\"emai^\": \"john@gmail.com\",
	\"password\": \"123456\"
}"



https://www.udemy.com/course/nodejs-api-masterclass/?couponCode=OCTOBER999
https://www.udemy.com/course/nodejs-api-masterclass/?couponCode=OCTOBER1399 



https://flaviocopes.com/

https://developer.mapquest.com/
